development:
  adapter:  mysql2
  encoding: utf8mb4
  database: <%= ENV['MYSQL_DATABASE'] || 'railsdm2018' %>
  username: <%= ENV['MYSQL_USER'] || 'root' %>
  password: <%= ENV['MYSQL_PASSWORD'] %>
  host:     <%= ENV['MYSQL_HOST'] || 'localhost' %>
  port:     <%= ENV['MYSQL_PORT'] || 3306 %>
